version: "3"
services:
  postgres:
    image: postgres:15
    container_name: postgres-django
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: eventosdb
    ports:
      - "5432:5432"
    volumes:
      - ../data/postgres:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"